### ISSUE TITLE
Integration with database has not been done properly, please look into it

### ISSUE THREAD

**Issue by HelloSumanShrestha** [HelloSumanShrestha/Farmer-s-App#3]
I've encountered a problem with the database integration, and it seems that it hasn't been done properly. Need to investigate and rectify the integration errors to ensure smooth functioning of the system.

**Comment by Prithak-Rai** [comment]
I've completed the investigation and resolution of the database integration issue. The connection to the database has been reviewed and confirmed to be set up correctly. 

Please feel free to review the changes and let me know if everything looks good from your end. If you have any further questions or concerns, don't hesitate to reach out.
