### ISSUE TITLE
sorting 

### ISSUE THREAD

**Issue by Devraj-098765** [HelloSumanShrestha/Farmer-s-App#8]
The sorting system currently displays all products on a single page. I want the products to be displayed in their respective categories, such as fruits, vegetables, etc.

**Comment by Devraj-098765** [comment]
sort dropdown is not aligned properly

**Comment by Devraj-098765** [comment]
this is the is screenshot of the error
![Uploading Screenshot 2024-05-18 204615.png…]()

**Comment by HelloSumanShrestha** [comment]
the error has been resolved. I will be closing this issue.

**Comment by Devraj-098765** [comment]
okey
