### ISSUE TITLE
#Footer section has irregular style in its navigation link property

### ISSUE THREAD

**Issue by Devraj-098765** [HelloSumanShrestha/Farmer-s-App#9]
the footer section has irregular style in it

**Comment by HelloSumanShrestha** [comment]
Can you please send the screensort of the issue?

**Comment by Devraj-098765** [comment]
![Screenshot 2024-05-18 205320](https://github.com/HelloSumanShrestha/Farmer-s-App/assets/119732347/da4f9c93-4278-47f8-a5a3-9dff8e5ba690)

**Comment by HelloSumanShrestha** [comment]
ok will be working on it

**Comment by sanskar800** [comment]
> the footer section has irregular style in it

The contact us not aligned properly.
